"""add_payroll_models

Revision ID: 1f5e399d8710
Revises: 2bd9258551ee
Create Date: 2026-08-03 09:11:15.966232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5e399d8710'
down_revision = '2bd9258551ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payrolls',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('medical_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('travel_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('special_allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('incentive', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provident_fund', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loan_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('insurance_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payrolls_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payrolls')),
    sa.UniqueConstraint('employee_id', 'month', 'year', name='uq_employee_month_year')
    )
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payrolls_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payrolls_status'), ['status'], unique=False)

    op.create_table('payroll_histories',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_payroll_histories_generated_by_users')),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], name=op.f('fk_payroll_histories_payroll_id_payrolls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_histories'))
    )
    with op.batch_alter_table('payroll_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_histories_payroll_id'), ['payroll_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_histories_payroll_id'))

    op.drop_table('payroll_histories')
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payrolls_status'))
        batch_op.drop_index(batch_op.f('ix_payrolls_employee_id'))

    op.drop_table('payrolls')
    # ### end Alembic commands ###
