"""add_employee_id_to_user

Revision ID: 7dbac638f77c
Revises: b191f9286a0a
Create Date: 2026-08-19 18:20:07.799865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbac638f77c'
down_revision = 'b191f9286a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_employee_id'), ['employee_id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_employee_id_employees'), 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_employee_id_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_employee_id'), type_='unique')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
