"""add_government_rule_models

Revision ID: 815b1d866e0f
Revises: 707d45b6a5be
Create Date: 2026-08-03 14:29:29.581259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815b1d866e0f'
down_revision = '707d45b6a5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_rules',
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_rules'))
    )
    with op.batch_alter_table('government_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_rules_rule_type'), ['rule_type'], unique=False)

    op.create_table('payroll_validation_logs',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], name=op.f('fk_payroll_validation_logs_payroll_id_payrolls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_validation_logs'))
    )
    with op.batch_alter_table('payroll_validation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_validation_logs_payroll_id'), ['payroll_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_validation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_validation_logs_payroll_id'))

    op.drop_table('payroll_validation_logs')
    with op.batch_alter_table('government_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_rules_rule_type'))

    op.drop_table('government_rules')
    # ### end Alembic commands ###
