"""add_attendance_model

Revision ID: 8a9b7d504ea4
Revises: acb4e4a35bd8
Create Date: 2026-08-02 19:51:29.147934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9b7d504ea4'
down_revision = 'acb4e4a35bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('working_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('early_leave_minutes >= 0', name=op.f('ck_attendances_ck_early_leave_non_negative')),
    sa.CheckConstraint('late_minutes >= 0', name=op.f('ck_attendances_ck_late_non_negative')),
    sa.CheckConstraint('overtime_hours >= 0', name=op.f('ck_attendances_ck_overtime_non_negative')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendances_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendances')),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_date')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_status'), ['status'], unique=False)
        batch_op.create_index('ix_employee_date', ['employee_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_date')
        batch_op.drop_index(batch_op.f('ix_attendances_status'))
        batch_op.drop_index(batch_op.f('ix_attendances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_date'))
        batch_op.drop_index('ix_attendance_status')

    op.drop_table('attendances')
    # ### end Alembic commands ###
