"""add_leave_encashment

Revision ID: b191f9286a0a
Revises: 815b1d866e0f
Create Date: 2026-08-04 18:04:33.075443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b191f9286a0a'
down_revision = '815b1d866e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_encashments',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('days_requested', sa.Integer(), nullable=False),
    sa.Column('amount_per_day', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_leave_encashments_approved_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_encashments_employee_id_employees')),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_encashments_leave_type_id_leave_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_encashments')),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_encashment_year')
    )
    with op.batch_alter_table('leave_encashments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_encashments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_encashments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_encashments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_encashments_status'))
        batch_op.drop_index(batch_op.f('ix_leave_encashments_employee_id'))

    op.drop_table('leave_encashments')
    # ### end Alembic commands ###
